<?php
// Do not edit this file outside of the component library as otherwise your changes will be lost with future updates.
function create_colour_data()
{
	if (function_exists('get_fields') && defined('THEMES_OPTIONS') && is_array(THEMES_OPTIONS)) {
		$colour_config                   = array();
		if (array_key_exists('post_id', $GLOBALS)) {
			$post = Timber::get_post($GLOBALS['post_id']);
			$colour_config['enable-custom-theme']   = $post->meta['enable_custom_theme_select'] ?? false;
		}
		$options                          = THEMES_OPTIONS;
		$colour_config['selectFieldNames']   = array(
			'page_theme'
		);
		if (is_array(MARKET_SETTINGS_OPTIONS) && array_key_exists('default_theme', MARKET_SETTINGS_OPTIONS)) {
			$colour_config['default-theme']   = MARKET_SETTINGS_OPTIONS['default_theme'];
			if (
				$options
				&& is_array($options)
				&& array_key_exists('themes', $options)
				&& is_array($options['themes'])
			) {
				foreach ($options['themes'] as $index => $value) {
					if (!$value['text_colours']) {
						return;
					}
					if (!$value['theme_colours']) {
						return;
					}
					$themeIndexName = 'theme-' . ($index + 1);
					$colour_config[$themeIndexName]         = array();
					$colour_config[$themeIndexName]['text'] =
						array_map(
							function ($item) {
								return $item['colour'];
							},
							$value['text_colours']
						);
					$colour_config[$themeIndexName]['colours'] =
						array_map(
							function ($item) {
								return $item['theme_colour'];
							},
							$value['theme_colours']
						);
					$colour_config[$themeIndexName]['links'] = $value['links'];
					$colour_config[$themeIndexName]['theme_primary_background_colour'] = $value['theme_primary_background_colour'];
					$colour_config[$themeIndexName]['theme_secondary_background_colour'] = $value['theme_secondary_background_colour'];
					$colour_config[$themeIndexName]['theme_tertiary_background_colour'] = $value['theme_tertiary_background_colour'];
					$colour_config[$themeIndexName]['theme_primary_text_colour'] = $value['theme_primary_text_colour'];
					$colour_config[$themeIndexName]['theme_secondary_text_colour'] = $value['theme_secondary_text_colour'];
					$colour_config[$themeIndexName]['theme_tertiary_text_colour'] = $value['theme_tertiary_text_colour'];
				}
			}
		}
		return $colour_config;
	} else {
		return array();
	}
}
